import { useMemo,useState } from 'react'
import Icon from './Icons'
import { defaultClipFx,soundPresets } from './project'
import type { AudioClip,AudioTrack,ClipFx,SoundPreset,TimelineSelection } from './types'
import { clipTimelineDuration,formatTime } from './utils'

function RangeControl({label,value,min,max,step,onChange,onStart,suffix='',format}:{label:string;value:number;min:number;max:number;step:number;onChange:(v:number)=>void;onStart:()=>void;suffix?:string;format?:(v:number)=>string}){const display=format?format(value):`${Number(value).toFixed(step<1?2:0)}${suffix}`,percent=((Number(value)-min)/(max-min))*100;return <label className="ax25-fx-control"><div><span>{label}</span><strong>{display}</strong></div><input style={{'--range':`${Math.max(0,Math.min(100,percent))}%`} as React.CSSProperties} type="range" min={min} max={max} step={step} value={value} onPointerDown={onStart} onChange={e=>onChange(Number(e.target.value))}/></label>}
function Toggle({label,note,checked,onChange}:{label:string;note:string;checked:boolean;onChange:(v:boolean)=>void}){return <button type="button" className={`ax25-fx-toggle ${checked?'on':''}`} onClick={()=>onChange(!checked)}><span><strong>{label}</strong><small>{note}</small></span><i><b/></i></button>}

type NumericKey=Exclude<keyof ClipFx,'compressor'|'limiter'|'reverse'|'preservePitch'|'motionMode'>
const ranges:Partial<Record<NumericKey,{label:string;min:number;max:number;step:number;suffix?:string;format?:(v:number)=>string}>>={
 gainDb:{label:'Gain',min:-18,max:8,step:.5,suffix:' dB'},pan:{label:'Pan',min:-1,max:1,step:.01,format:v=>Math.abs(v)<.01?'Center':v<0?`${Math.round(Math.abs(v)*100)}% L`:`${Math.round(v*100)}% R`},bassDb:{label:'Bass',min:-12,max:12,step:.5,suffix:' dB'},midDb:{label:'Mid',min:-12,max:12,step:.5,suffix:' dB'},trebleDb:{label:'Treble',min:-12,max:12,step:.5,suffix:' dB'},delayMs:{label:'Delay time',min:0,max:900,step:5,suffix:' ms'},feedback:{label:'Feedback',min:0,max:.72,step:.01,format:v=>`${Math.round(v*100)}%`},delayWet:{label:'Delay wet',min:0,max:.55,step:.01,format:v=>`${Math.round(v*100)}%`},reverb:{label:'Reverb',min:0,max:.75,step:.01,format:v=>`${Math.round(v*100)}%`},fadeIn:{label:'Fade in',min:0,max:12,step:.05,suffix:' s'},fadeOut:{label:'Fade out',min:0,max:12,step:.05,suffix:' s'},speed:{label:'Speed',min:.5,max:1.6,step:.01,format:v=>`${v.toFixed(2)}×`},tapePitchSemitones:{label:'Tape pitch',min:-12,max:12,step:1,format:v=>`${v>0?'+':''}${v} st`},motionDepth:{label:'Motion depth',min:0,max:.98,step:.01,format:v=>`${Math.round(v*100)}%`},motionHz:{label:'Motion speed',min:.03,max:.8,step:.01,format:v=>`${v.toFixed(2)} Hz`}
}
function PresetSettings({preset,draft,onChange}:{preset:SoundPreset;draft:Partial<ClipFx>;onChange:(key:keyof ClipFx,value:any)=>void}){return <div className="ax25-preset-controls">{(Object.keys(preset.patch) as (keyof ClipFx)[]).map(key=>{const value=(draft as any)[key]??(preset.patch as any)[key];if(key==='compressor')return <Toggle key={key} label="Compressor" note="Smooth peaks" checked={Boolean(value)} onChange={v=>onChange(key,v)}/>;if(key==='limiter')return <Toggle key={key} label="Limiter" note="Protect output" checked={Boolean(value)} onChange={v=>onChange(key,v)}/>;if(key==='reverse')return <Toggle key={key} label="Reverse" note="Play this edit backwards" checked={Boolean(value)} onChange={v=>onChange(key,v)}/>;if(key==='preservePitch')return <Toggle key={key} label="Pitch lock" note="Keep pitch closer while speed changes" checked={Boolean(value)} onChange={v=>onChange(key,v)}/>;if(key==='motionMode')return <div key={key} className="ax25-motion-switch"><span>Stereo motion</span><div>{(['off','8d','16d'] as const).map(mode=><button type="button" key={mode} className={value===mode?'active':''} onClick={()=>onChange(key,mode)}>{mode==='off'?'Off':mode.toUpperCase()}</button>)}</div></div>;const cfg=ranges[key as NumericKey];if(!cfg)return null;return <RangeControl key={key} label={cfg.label} value={Number(value)} min={cfg.min} max={cfg.max} step={cfg.step} suffix={cfg.suffix} format={cfg.format} onStart={()=>{}} onChange={v=>onChange(key,v)}/>})}</div>}

type Props={clip:AudioClip|null;track:AudioTrack|null;selection:TimelineSelection;onPatchClipFx:(patch:Partial<ClipFx>)=>void;onCheckpoint:()=>void;onEditEnd:()=>void;onPreset:(preset:SoundPreset)=>void;onMakeRegion:()=>void;onReset:()=>void}
type Tab='presets'|'tone'|'space'|'motion'|'clip'

export default function Inspector({clip,track,selection,onPatchClipFx,onCheckpoint,onEditEnd,onPreset,onMakeRegion,onReset}:Props){
 const [tab,setTab]=useState<Tab>('presets'),[search,setSearch]=useState(''),[chosen,setChosen]=useState<SoundPreset|null>(null),[draft,setDraft]=useState<Partial<ClipFx>>({}),[group,setGroup]=useState('All')
 const hasSelection=selection.end>selection.start+.005,fx=clip?.fx||defaultClipFx,edited=useMemo(()=>!!clip&&JSON.stringify(clip.fx)!==JSON.stringify(defaultClipFx),[clip]),patch=(p:Partial<ClipFx>)=>onPatchClipFx(p)
 const choose=(p:SoundPreset)=>{setChosen(p);setDraft({...p.patch})},setD=(key:keyof ClipFx,value:any)=>setDraft(cur=>({...cur,[key]:value}))
 const groups=useMemo(()=>['All',...new Set(soundPresets.map(p=>p.group))],[])
 const filtered=soundPresets.filter(p=>(group==='All'||p.group===group)&&(p.name+' '+p.group+' '+p.note).toLowerCase().includes(search.toLowerCase()))
 const closePreset=()=>{setChosen(null);setDraft({})}
 return <aside className="ax25-inspector" onPointerUp={onEditEnd} onKeyUp={onEditEnd}>
  <header className="ax25-inspector-head"><div><Icon name="waveform" size={18}/></div><span><small>CONTROL DOCK</small><strong>{clip?clip.name:'Select audio'}</strong><em>{track?.name||'Choose a waveform to begin'}</em></span></header>
  <nav className="ax25-inspector-tabs">{([['presets','Presets'],['tone','Tone'],['space','Space'],['motion','Motion'],['clip','Clip']] as const).map(([id,label])=><button key={id} type="button" className={tab===id?'active':''} onClick={()=>{setTab(id);closePreset()}}>{label}</button>)}</nav>
  {!clip?<div className="ax25-inspector-empty"><span>∿</span><h3>Select a waveform</h3><p>Tap a bright audio clip. Its settings open here. The faded waveform underneath is only your original-source reference.</p></div>:<div className="ax25-inspector-body">
   {hasSelection&&<div className="ax25-selection-card"><span><small>ACTIVE RANGE</small><strong>{formatTime(selection.start,true)} → {formatTime(selection.end,true)}</strong><em>{formatTime(selection.end-selection.start,true)} selected</em></span><button onClick={onMakeRegion}>Use this range</button></div>}
   {tab==='presets'&&(!chosen?<section className="ax25-preset-panel"><div className="ax25-preset-steps"><span><b>1</b> Choose</span><i>→</i><span><b>2</b> Adjust</span><i>→</i><span><b>3</b> Apply</span></div><div className="ax25-panel-note"><Icon name="spark" size={15}/><p><b>Nothing applies on click.</b> Opening a preset only shows its own controls. You decide when to Apply.</p></div><label className="ax25-preset-search"><span>Find a preset</span><input aria-label="Find a preset" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search 30 presets…"/></label><div className="ax25-preset-groups">{groups.map(g=><button type="button" key={g} className={group===g?'active':''} onClick={()=>setGroup(g)}>{g}</button>)}</div><div className="ax25-preset-grid">{filtered.map(p=><button type="button" key={p.id} onClick={()=>choose(p)}><span>✦</span><small>{p.group}</small><strong>{p.name}</strong><em>{p.note}</em><b>Adjust settings <span>↗</span></b></button>)}</div>{!filtered.length&&<div className="ax25-preset-empty">No preset matches this search.</div>}</section>:<section className="ax25-preset-editor embedded" aria-label={`${chosen.name} preset settings`}><header><button className="back" type="button" onClick={closePreset}>← Presets</button><div><small>STEP 2 / ADJUST</small><h3>{chosen.name}</h3><p>Only the controls used by this preset are shown below. Your audio is unchanged until Step 3.</p></div></header><div className="ax25-preset-editor-scroll"><PresetSettings preset={chosen} draft={draft} onChange={setD}/></div><footer><button type="button" onClick={closePreset}>Cancel</button><button type="button" className="apply" onClick={()=>{onPreset({...chosen,patch:draft});closePreset()}}>Apply {chosen.name} <span>↗</span></button></footer></section>)}
   {tab==='tone'&&<section className="ax25-control-section"><header><span>LEVEL & TONE</span><small>Manual controls · changes appear in Applied Edits</small></header><RangeControl label="Gain" value={fx.gainDb} min={-18} max={8} step={.5} suffix=" dB" onStart={onCheckpoint} onChange={v=>patch({gainDb:v})}/><RangeControl label="Bass" value={fx.bassDb} min={-12} max={12} step={.5} suffix=" dB" onStart={onCheckpoint} onChange={v=>patch({bassDb:v})}/><RangeControl label="Mid" value={fx.midDb} min={-12} max={12} step={.5} suffix=" dB" onStart={onCheckpoint} onChange={v=>patch({midDb:v})}/><RangeControl label="Treble" value={fx.trebleDb} min={-12} max={12} step={.5} suffix=" dB" onStart={onCheckpoint} onChange={v=>patch({trebleDb:v})}/><Toggle label="Compressor" note="Smooth peaks" checked={fx.compressor} onChange={v=>{onCheckpoint();patch({compressor:v})}}/><Toggle label="Limiter" note="Protect output" checked={fx.limiter} onChange={v=>{onCheckpoint();patch({limiter:v})}}/></section>}
   {tab==='space'&&<section className="ax25-control-section"><header><span>SPACE</span><small>Reverb + echo</small></header><RangeControl label="Reverb" value={fx.reverb} min={0} max={.75} step={.01} onStart={onCheckpoint} format={v=>`${Math.round(v*100)}%`} onChange={v=>patch({reverb:v})}/><RangeControl label="Delay time" value={fx.delayMs} min={0} max={900} step={5} suffix=" ms" onStart={onCheckpoint} onChange={v=>patch({delayMs:v})}/><RangeControl label="Delay wet" value={fx.delayWet} min={0} max={.55} step={.01} onStart={onCheckpoint} format={v=>`${Math.round(v*100)}%`} onChange={v=>patch({delayWet:v})}/><RangeControl label="Feedback" value={fx.feedback} min={0} max={.72} step={.01} onStart={onCheckpoint} format={v=>`${Math.round(v*100)}%`} onChange={v=>patch({feedback:v})}/></section>}
   {tab==='motion'&&<section className="ax25-control-section"><header><span>STEREO MOTION</span><small>8D / 16D movement</small></header><div className="ax25-motion-switch"><span>Mode</span><div><button className={fx.motionMode==='off'?'active':''} onClick={()=>{onCheckpoint();patch({motionMode:'off'})}}>Off</button><button className={fx.motionMode==='8d'?'active':''} onClick={()=>{onCheckpoint();patch({motionMode:'8d'})}}>8D</button><button className={fx.motionMode==='16d'?'active':''} onClick={()=>{onCheckpoint();patch({motionMode:'16d'})}}>16D</button></div></div><RangeControl label="Depth" value={fx.motionDepth} min={0} max={.98} step={.01} onStart={onCheckpoint} format={v=>`${Math.round(v*100)}%`} onChange={v=>patch({motionDepth:v})}/><RangeControl label="Speed" value={fx.motionHz} min={.03} max={.8} step={.01} onStart={onCheckpoint} format={v=>`${v.toFixed(2)} Hz`} onChange={v=>patch({motionHz:v})}/><RangeControl label="Pan" value={fx.pan} min={-1} max={1} step={.01} onStart={onCheckpoint} format={v=>Math.abs(v)<.01?'Center':v<0?`${Math.round(Math.abs(v)*100)}% L`:`${Math.round(v*100)}% R`} onChange={v=>patch({pan:v})}/></section>}
   {tab==='clip'&&<section className="ax25-control-section"><header><span>CLIP</span><small>Direction · speed · fades</small></header><Toggle label="Reverse" note="Play backwards" checked={fx.reverse} onChange={v=>{onCheckpoint();patch({reverse:v})}}/><RangeControl label="Speed" value={fx.speed} min={.5} max={1.6} step={.01} onStart={onCheckpoint} format={v=>`${v.toFixed(2)}×`} onChange={v=>patch({speed:v})}/><Toggle label="Pitch lock" note="Keep pitch closer while speed changes" checked={fx.preservePitch===true} onChange={v=>{onCheckpoint();patch({preservePitch:v})}}/><RangeControl label="Tape pitch" value={fx.tapePitchSemitones} min={-12} max={12} step={1} onStart={onCheckpoint} format={v=>`${v>0?'+':''}${v} st`} onChange={v=>patch({tapePitchSemitones:v})}/><RangeControl label="Fade in" value={fx.fadeIn} min={0} max={Math.max(.25,Math.min(12,clipTimelineDuration(clip)))} step={.05} suffix=" s" onStart={onCheckpoint} onChange={v=>patch({fadeIn:v})}/><RangeControl label="Fade out" value={fx.fadeOut} min={0} max={Math.max(.25,Math.min(12,clipTimelineDuration(clip)))} step={.05} suffix=" s" onStart={onCheckpoint} onChange={v=>patch({fadeOut:v})}/><div className="ax25-clip-info"><span><small>Timeline start</small><b>{formatTime(clip.start,true)}</b></span><span><small>Edited length</small><b>{formatTime(clipTimelineDuration(clip),true)}</b></span><span><small>Source range</small><b>{formatTime(clip.offset,true)} → {formatTime(clip.offset+clip.duration,true)}</b></span></div><button className="ax25-reset-button" disabled={!edited} onClick={onReset}>Reset selected clip effects</button></section>}
  </div>}
 </aside>
}
