import { useEffect,useRef,useState } from 'react'
import { formatTime } from './utils'
export default function Recorder({onFinish,onClose}:{onFinish:(file:File)=>void;onClose:()=>void}){
 const [state,setState]=useState<'idle'|'recording'|'paused'|'ready'>('idle'),[seconds,setSeconds]=useState(0),[message,setMessage]=useState(''),[file,setFile]=useState<File|null>(null),[url,setUrl]=useState(''),[starting,setStarting]=useState(false)
 const recorder=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),chunks=useRef<Blob[]>([]),timer=useRef<ReturnType<typeof setInterval>>(),elapsed=useRef(0),mounted=useRef(true)
 const stop=()=>{clearInterval(timer.current);if(recorder.current&&recorder.current.state!=='inactive')recorder.current.stop();stream.current?.getTracks().forEach(track=>track.stop())}
 const start=async()=>{setStarting(true);setMessage('');try{if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)throw new Error('Microphone recording needs a supported browser and HTTPS.');const source=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true},video:false});if(!mounted.current){source.getTracks().forEach(t=>t.stop());return}stream.current=source;const mime=['audio/webm;codecs=opus','audio/mp4','audio/ogg;codecs=opus'].find(m=>MediaRecorder.isTypeSupported(m));const r=new MediaRecorder(source,mime?{mimeType:mime}:undefined);recorder.current=r;chunks.current=[];elapsed.current=0;setSeconds(0);setFile(null);r.ondataavailable=e=>{if(e.data.size)chunks.current.push(e.data)};r.onstop=()=>{source.getTracks().forEach(t=>t.stop());if(!mounted.current)return;const type=r.mimeType||'audio/webm',extension=type.includes('mp4')?'m4a':type.includes('ogg')?'ogg':'webm',take=new File(chunks.current,`Audixo-take-${Date.now()}.${extension}`,{type});setFile(take);setState('ready')};r.start(1000);setState('recording');timer.current=setInterval(()=>{if(r.state==='recording'){elapsed.current++;setSeconds(elapsed.current);if(elapsed.current>=600)stop()}},1000)}catch(e){setMessage((e as Error).message||'Microphone access was not granted. You can still import an audio file.')}finally{setStarting(false)}}
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;stop()}},[])
 useEffect(()=>{if(!file)return;const u=URL.createObjectURL(file);setUrl(u);return()=>URL.revokeObjectURL(u)},[file])
 return <section className="nx-recorder nx-glass" aria-label="Microphone recorder"><header><div><small>RECORD A NEW TAKE</small><h2>Your voice. In the mix.</h2></div><button onClick={onClose} aria-label="Close recorder">×</button></header><div className={`nx-record-display ${state==='recording'?'recording':''}`}><i/><output>{formatTime(seconds,true)}</output><span>{state==='recording'?'RECORDING':state==='paused'?'PAUSED':state==='ready'?'TAKE READY':'MICROPHONE'}</span></div><p>Recording stays on this device. Click Record and allow microphone access. Up to 10 minutes per take.</p><div className="nx-record-actions">{(state==='idle'||state==='ready')&&<button className="button button-primary" disabled={starting} onClick={start}>{starting?'Opening microphone…':state==='ready'?'Record another take':'Record'}</button>}{(state==='recording'||state==='paused')&&<><button className="button button-glass" onClick={()=>{const r=recorder.current;if(!r)return;if(r.state==='recording'){r.pause();setState('paused')}else{r.resume();setState('recording')}}}>{state==='paused'?'Resume':'Pause'}</button><button className="button button-primary" onClick={stop}>Stop recording</button></>}{state==='ready'&&file&&<button className="button button-primary" onClick={()=>{onFinish(file);onClose()}}>Add take to timeline ↗</button>}</div>{file&&<audio controls src={url} preload="metadata"/>}{message&&<p role="alert">{message}</p>}</section>
}
