import { useEffect,useState } from 'react'
import { Link } from 'react-router-dom'
import Logo from '../components/Logo'
import { formatTime } from './utils'
import type { TimelineSelection } from './types'

type Props={name:string;playing:boolean;time:number;duration:number;onPlay:()=>void;onImport:()=>void;onExport:()=>void;onLibrary:()=>void;onRecord:()=>void;onDuplicate:()=>void;onKeepRange:()=>void;onUndo:()=>void;onRedo:()=>void;canUndo:boolean;canRedo:boolean;sourceStart:number;sourceEnd:number;sourceDuration:number;onSource:(a:number,b:number)=>void;selected:boolean;cutMode:boolean;onCutMode:(b:boolean)=>void;selection:TimelineSelection;onSelection:(s:TimelineSelection)=>void;onCut:()=>void;allTracks:boolean;onAllTracks:(v:boolean)=>void;onFit:()=>void;scale:number;onScale:(n:number)=>void}

export default function Transport(p:Props){
 const start=p.cutMode?p.selection.start:p.sourceStart,end=p.cutMode?p.selection.end:p.sourceEnd,max=p.cutMode?p.duration:p.sourceDuration
 const [a,setA]=useState(String(Number(start.toFixed(3)))),[b,setB]=useState(String(Number(end.toFixed(3))))
 useEffect(()=>{setA(String(Number(start.toFixed(3))));setB(String(Number(end.toFixed(3))))},[start,end,p.cutMode,p.selected])
 const apply=()=>{const first=Number(a),last=Number(b);if(!a||!b||![first,last].every(Number.isFinite)||last<=first||first<0||last>max){setA(String(Number(start.toFixed(3))));setB(String(Number(end.toFixed(3))));return}if(first===start&&last===end)return;p.cutMode?p.onSelection({...p.selection,start:first,end:last}):p.onSource(first,last)}
 return <>
  <header className="ax25-studio-header"><Link to="/" className="ax25-studio-brand" aria-label="Audixo home"><Logo/></Link><div className="ax25-project-title"><small>NOW EDITING</small><strong>{p.name}</strong></div><nav><Link to="/tools/vocals">Vocals</Link><button className="library" onClick={p.onLibrary}>Library</button><button className="record" onClick={p.onRecord}>Record</button><button className="soft import" onClick={p.onImport}>+ Import audio</button><button className="export" disabled={!p.duration} onClick={p.onExport}>Export <span>↗</span></button></nav></header>
  <section className="ax25-transport-bar"><div className="ax25-play-group"><button className="icon" aria-label="Undo" disabled={!p.canUndo} onClick={p.onUndo}>↶</button><button className="icon" aria-label="Redo" disabled={!p.canRedo} onClick={p.onRedo}>↷</button><button className="play" disabled={!p.duration} aria-label={p.playing?'Pause':'Play'} onClick={p.onPlay}>{p.playing?'Ⅱ':'▶'}</button><output>{formatTime(p.time,true)} <small>/ {formatTime(p.duration,true)}</small></output></div><div className="ax25-view-tools"><button disabled={!p.selected} onClick={p.onDuplicate}>⧉ {p.cutMode?'Duplicate range':'Duplicate audio'}</button><button onClick={p.onFit}>Fit timeline</button><label><span>Zoom</span><input aria-label="Timeline zoom" type="range" min="-9.2" max="5.2" step=".05" value={Math.log(Math.max(.0001,p.scale))} onChange={e=>p.onScale(Math.exp(+e.target.value))}/></label></div></section>
  <section className="ax25-edit-toolbar"><div className="ax25-edit-mode"><button className={!p.cutMode?'active':''} onClick={()=>p.onCutMode(false)}><span>↔</span><b>Trim edges</b><small>Shape start / end</small></button><button className={p.cutMode?'active':''} onClick={()=>p.onCutMode(true)}><span>⌁</span><b>Select range</b><small>Work on the middle</small></button></div><div className="ax25-time-fields"><label><span>{p.cutMode?'Selection start':'Source start'}</span><div><input aria-label="Start seconds" type="number" min="0" step=".001" max={max} disabled={!p.selected} value={a} onChange={e=>setA(e.target.value)} onBlur={apply} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur()}}/><b>s</b></div></label><label><span>{p.cutMode?'Selection end':'Source end'}</span><div><input aria-label="End seconds" type="number" min=".01" step=".001" max={max} disabled={!p.selected} value={b} onChange={e=>setB(e.target.value)} onBlur={apply} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur()}}/><b>s</b></div></label></div>{p.cutMode?<div className="ax25-range-actions"><label><input type="checkbox" checked={p.allTracks} onChange={e=>p.onAllTracks(e.target.checked)}/><span>All tracks</span></label><button disabled={!p.selected||end<=start} onClick={p.onKeepRange}>Keep range</button><button className="danger" disabled={!p.selected||end<=start} onClick={p.onCut}>Remove & join</button></div>:<div className="ax25-trim-help"><span>TIP</span><p>Drag the bright edge handles. The full original waveform remains visible behind the active audio.</p></div>}</section>
 </>
}
