import test from 'node:test'
import assert from 'node:assert/strict'
import {createProject,createTrack,createClip} from '../src/editor/project'
import {edgeRange,setClipSourceRange,cutMiddle,fitScale} from '../src/editor/editing'
import {projectDuration,clipTimelineDuration,findClip} from '../src/editor/utils'
function fixture(length=100){const project=createProject(),track=createTrack('Audio'),clip=createClip({bufferId:'source',fileName:'test',duration:length});track.clips=[clip];project.tracks=[track];return {project,track,clip}}
test('two-hour audio remains fully addressable and fit scale is never zero',()=>{const {project}=fixture(7200);assert.equal(projectDuration(project),7200);for(const n of [240,375,768,1400]){const scale=fitScale(7200,n);assert.ok(scale>0);assert.ok(Number.isFinite(scale));assert.ok(7200*scale<=Math.max(240,n))}})
test('direct handles preserve full source and allow extension back',()=>{const {project,clip}=fixture();assert.deepEqual(edgeRange(clip,'start',12,100),{start:12,end:100});assert.ok(setClipSourceRange(project,clip.id,12,88,100));assert.equal(clip.offset,12);assert.equal(clip.duration,76);assert.equal(clip.start,0);assert.deepEqual(edgeRange(clip,'start',-12,100),{start:0,end:88});assert.ok(setClipSourceRange(project,clip.id,0,100,100));assert.equal(clip.duration,100)})
test('middle cut preserves the first and last samples and closes the gap',()=>{const {project,track}=fixture();assert.ok(cutMiddle(project,track.id,30,50));assert.equal(track.clips.length,2);assert.equal(track.clips[0].offset,0);assert.equal(track.clips[0].duration,30);assert.equal(track.clips[1].start,30);assert.equal(track.clips[1].offset,50);assert.equal(track.clips[1].duration,50);assert.equal(projectDuration(project),80)})
test('cut all tracks preserves synchronized stems',()=>{const {project,track}=fixture();const second=createTrack('Vocal');second.clips=[createClip({bufferId:'two',fileName:'vocal',duration:100})];project.tracks.push(second);cutMiddle(project,track.id,10,20,true);for(const t of project.tracks){assert.equal(t.clips[1].start,10);assert.equal(t.clips[1].offset,20)}assert.equal(projectDuration(project),90)})
test('middle cut in a rate-shifted clip uses source seconds correctly',()=>{const {project,track,clip}=fixture();clip.fx.speed=.5;cutMiddle(project,track.id,20,40);assert.equal(track.clips[0].duration,10);assert.equal(track.clips[1].offset,20);assert.equal(projectDuration(project),180)})
test('invalid source ranges never introduce NaN',()=>{const {project,clip}=fixture();assert.equal(setClipSourceRange(project,clip.id,NaN,5,100),false);assert.equal(setClipSourceRange(project,clip.id,0,Infinity,100),false);assert.ok(Number.isFinite(clip.duration))})
test('reverse middle cut keeps source offsets correct',()=>{const {project,track,clip}=fixture();clip.fx.reverse=true;cutMiddle(project,track.id,30,50);assert.equal(track.clips[0].offset,70);assert.equal(track.clips[1].offset,0);assert.equal(track.clips[1].duration,50)})

test('direct edge trimming follows playback order for reversed clips',()=>{const {clip}=fixture();clip.fx.reverse=true;assert.deepEqual(edgeRange(clip,'start',10,100),{start:0,end:90});assert.deepEqual(edgeRange(clip,'end',-10,100),{start:10,end:100})})

import {addCut,addEffect,addTrim,removeEdit,retainSources,rebuildEdits,targetsFor} from '../src/editor/editRack'
test('removing one preset restores its settings while preserving another preset',()=>{const {project,clip}=fixture();const targets=targetsFor(project,clip.id);addEffect(project,targets,{delayMs:300,delayWet:.2},'Echo');const echo=project.edits![0].id;addEffect(project,targets,{speed:.8,reverb:.3},'Slow + Reverb');removeEdit(project,echo);assert.equal(project.tracks[0].clips[0].fx.delayWet,0);assert.equal(project.tracks[0].clips[0].fx.speed,.8);assert.equal(project.tracks[0].clips[0].fx.reverb,.3);assert.equal(projectDuration(project),125)})
test('removing middle cut restores audio without shifting a later ranged effect',()=>{const {project,track,clip}=fixture();addCut(project,{trackId:track.id,start:20,end:40});const cut=project.edits![0].id;const later=project.tracks[0].clips[1];const target=targetsFor(project,later.id,{trackId:track.id,start:30,end:40});assert.equal(target[0].start,50);addEffect(project,target,{reverb:.5},'Range Reverb');removeEdit(project,cut);const affected=project.tracks[0].clips.find(c=>c.fx.reverb===.5)!;assert.equal(affected.offset,50);assert.equal(affected.duration,10);assert.equal(affected.start,50);assert.equal(projectDuration(project),100)})
test('removing trim restores full recording and keeps active effects',()=>{const {project,clip}=fixture();const targets=targetsFor(project,clip.id);addEffect(project,targets,{delayWet:.25},'Echo');addTrim(project,project.tracks[0].clips[0].id,10,80,100);assert.equal(projectDuration(project),70);removeEdit(project,project.edits!.find(op=>op.kind==='trim')!.id);assert.equal(projectDuration(project),100);assert.equal(project.tracks[0].clips[0].fx.delayWet,.25)})
test('ranged effects do not modify unselected source seconds',()=>{const {project,track,clip}=fixture();const targets=targetsFor(project,clip.id,{trackId:track.id,start:25,end:40});addEffect(project,targets,{speed:.5},'Slow range');assert.deepEqual(project.tracks[0].clips.map(c=>[c.offset,c.duration,c.fx.speed]),[[0,25,1],[25,15,.5],[40,60,1]]);assert.equal(projectDuration(project),115)})
test('reverse cut restoration preserves playback order and source anchors',()=>{const {project,track,clip}=fixture();addEffect(project,targetsFor(project,clip.id),{reverse:true},'Reverse');addCut(project,{trackId:track.id,start:20,end:40});const out=project.tracks[0].clips;assert.equal(out[0].offset,80);assert.equal(out[1].offset,0);assert.equal(projectDuration(project),80);removeEdit(project,project.edits!.find(op=>op.kind==='cut')!.id);assert.equal(projectDuration(project),100);assert.equal(project.tracks[0].clips[0].fx.reverse,true)})
test('independent source tracks survive edit removal, mute and added files',()=>{const {project,track,clip}=fixture();retainSources(project);addEffect(project,targetsFor(project,clip.id),{reverb:.3},'Reverb');const second=createTrack('Drums');second.clips=[createClip({bufferId:'drums',fileName:'drums',duration:100})];project.sources!.push(second);project.sources![0].muted=true;rebuildEdits(project);removeEdit(project,project.edits![0].id);assert.equal(project.tracks.length,2);assert.equal(project.tracks[0].muted,true);assert.equal(project.tracks[1].name,'Drums');assert.equal(project.tracks[0].clips[0].fx.reverb,0)})
test('trimming an effect segment preserves adjacent unselected audio',()=>{const {project,track,clip}=fixture();addEffect(project,targetsFor(project,clip.id,{trackId:track.id,start:20,end:40}),{reverb:.3},'Range Reverb');const selected=project.tracks[0].clips.find(c=>c.offset===20)!;addTrim(project,selected.id,25,35,100);assert.deepEqual(project.tracks[0].clips.map(c=>[c.offset,c.duration]),[[0,20],[25,10],[40,60]]);assert.equal(projectDuration(project),90);removeEdit(project,project.edits!.find(op=>op.kind==='trim')!.id);assert.equal(projectDuration(project),100);assert.equal(project.tracks[0].clips.find(c=>c.fx.reverb===.3)!.duration,20)})
test('manual slider changes update one removable layer across existing effects',()=>{const {project,clip}=fixture();const targets=targetsFor(project,clip.id);addEffect(project,targets,{speed:.8},'Slow');for(let i=0;i<10;i++)addEffect(project,targetsFor(project,project.tracks[0].clips[0].id),{delayWet:i/100},'Echo','manual:Echo');assert.equal(project.edits!.length,2);removeEdit(project,project.edits![1].id);assert.equal(project.tracks[0].clips[0].fx.speed,.8);assert.equal(project.tracks[0].clips[0].fx.delayWet,0)})
test('reapplying a preset updates its existing layer and makes it the latest override',()=>{const {project,clip}=fixture();const targets=targetsFor(project,clip.id);addEffect(project,targets,{delayWet:.2},'Echo','preset:echo');const echo=project.edits![0].id;addEffect(project,targets,{delayWet:.1,reverb:.3},'Space','preset:space');addEffect(project,targets,{delayWet:.25},'Echo','preset:echo');assert.equal(project.edits!.length,2);assert.equal(project.edits![1].id,echo);assert.equal(project.tracks[0].clips[0].fx.delayWet,.25);removeEdit(project,echo);assert.equal(project.tracks[0].clips[0].fx.delayWet,.1);assert.equal(project.tracks[0].clips[0].fx.reverb,.3)})

import {duplicateAudio,clearEdits} from '../src/editor/editRack'
import {soundPresets} from '../src/editor/project'
import {retainedRanges,sliceAudio} from '../src/services/audioSlices'
test('duplicate appends current audio and removing it keeps original effects',()=>{const {project,clip}=fixture(40);addEffect(project,targetsFor(project,clip.id),{speed:.8,delayWet:.2},'Slow echo');const id=project.tracks[0].clips[0].id;duplicateAudio(project,id);assert.equal(projectDuration(project),100);assert.equal(project.tracks[0].clips[1].start,50);assert.equal(project.tracks[0].clips[1].fx.speed,.8);removeEdit(project,project.edits!.find(e=>e.kind==='duplicate')!.id);assert.equal(projectDuration(project),50);assert.equal(project.tracks[0].clips[0].fx.delayWet,.2);assert.ok(project.edits!.every(e=>e.label!=='Copied sound'))})
test('duplicate selected seconds respects speed and reverse source anchors',()=>{const {project,track,clip}=fixture(40);addEffect(project,targetsFor(project,clip.id),{reverse:true,speed:.5},'Reverse slow');duplicateAudio(project,project.tracks[0].clips[0].id,{trackId:track.id,start:10,end:30});const copy=project.tracks[0].clips[1];assert.equal(copy.start,80);assert.equal(copy.offset,25);assert.equal(copy.duration,10);assert.equal(copy.fx.reverse,true);assert.equal(projectDuration(project),100)})
test('clear edits restores sources and removes duplicate copies',()=>{const {project,clip}=fixture(40);duplicateAudio(project,clip.id);addEffect(project,targetsFor(project,project.tracks[0].clips[0].id),{reverb:.3},'Reverb');clearEdits(project);assert.equal(projectDuration(project),40);assert.equal(project.tracks[0].clips.length,1);assert.equal(project.tracks[0].clips[0].fx.reverb,0);assert.equal(project.edits!.length,0)})
test('keep range via outside cuts is removable independently',()=>{const {project,track}=fixture(60);addCut(project,{trackId:track.id,start:30,end:60});addCut(project,{trackId:track.id,start:0,end:20});assert.equal(projectDuration(project),10);assert.equal(project.tracks[0].clips[0].offset,20);removeEdit(project,project.edits![0].id);assert.equal(projectDuration(project),40);assert.equal(project.tracks[0].clips[0].offset,20)})
test('sound collection has exactly 30 focused working presets',()=>{assert.equal(soundPresets.length,30);assert.equal(new Set(soundPresets.map(p=>p.id)).size,30);for(const preset of soundPresets){assert.ok(Object.keys(preset.patch).length);for(const [key,v] of Object.entries(preset.patch)){assert.ok(key in clipFxKeys);if(typeof v==='number')assert.ok(Number.isFinite(v))}}})
const clipFxKeys=createClip({bufferId:'x',fileName:'x',duration:1}).fx
test('retained ranges join overlapping middle cuts without duplicating retained audio',()=>{assert.deepEqual(retainedRanges({start:5,end:90},[{start:20,end:30},{start:25,end:40},{start:80,end:120}]),[{start:5,end:20},{start:40,end:80}]);assert.throws(()=>retainedRanges({start:0,end:10},[{start:0,end:10}]),/Keep/);assert.throws(()=>retainedRanges({start:NaN,end:10},[]),/valid/)})
test('local WAV slicing keeps exact sample boundaries and rewrites RIFF sizes',async()=>{const bytes=new Uint8Array(44+2000),view=new DataView(bytes.buffer),str=(pos:number,s:string)=>[...s].forEach((c,i)=>bytes[pos+i]=c.charCodeAt(0));str(0,'RIFF');view.setUint32(4,2036,true);str(8,'WAVE');str(12,'fmt ');view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,1,true);view.setUint32(24,100,true);view.setUint32(28,200,true);view.setUint16(32,2,true);view.setUint16(34,16,true);str(36,'data');view.setUint32(40,2000,true);for(let i=0;i<1000;i++)view.setInt16(44+i*2,i,true);const result=await sliceAudio(new Blob([bytes]),[{start:1,end:2},{start:8,end:10}]);assert.equal(result.duration,3);const output=new DataView(await result.blob.arrayBuffer());assert.equal(output.getUint32(40,true),600);assert.equal(output.getUint32(4,true),636);assert.equal(output.getInt16(44,true),100);assert.equal(output.getInt16(244,true),800);assert.equal(output.getInt16(642,true),999)})
