import { Link } from 'react-router-dom'
import Seo from '../components/Seo'
import SiteShell from '../components/SiteShell'
import HeroAudioVisual from '../components/HeroAudioVisual'

const values=[
 ['01','Creator-first flow','Start with a song, voice take or rough idea and shape it without losing the source.'],
 ['02','Visible decisions','Waveforms, ranges, stems and clips stay visible so every edit has context.'],
 ['03','Section-level freedom','Split mashup clips, replace music or rebuild only the part that needs work.'],
 ['04','Focused depth','Quick tools stay simple; Full Studio opens deeper controls only when you need them.']
]

export default function About(){return <SiteShell><Seo title="About Audixo Studio — Creator Audio Tools by Nexivo" description="Learn how Audixo turns trimming, mashups, stem separation and creative audio editing into a clear browser workflow, powered by Nexivo." path="/about"/><main className="page-shell ax26-about ax33-about">
 <section className="ax26-about-hero ax33-about-hero"><div><div className="ax25-kicker"><i/> ABOUT AUDIXO STUDIO</div><h1>Audio tools that stay<br/><em>clear while you create.</em></h1><p>Audixo is a browser audio studio built around direct visual editing: trim the source, split a mashup, separate stems, shape a section and export without losing sight of the original audio.</p><div className="ax26-about-actions"><Link to="/editor" className="ax25-primary-button">Open the Studio <span>↗</span></Link><Link to="/how-it-works" className="ax25-text-action">See the workflow <span>→</span></Link></div></div><div className="ax26-about-visual"><HeroAudioVisual front/></div></section>
 <section className="ax32-about-ribbon"><span>TRIM</span><i/><span>MASHUP</span><i/><span>STEMS</span><i/><span>EFFECTS</span><i/><span>EXPORT</span></section>
 <section className="ax33-about-story"><article><small>WHY AUDIXO</small><h2>Less interface noise.<br/><em>More audible control.</em></h2><p>Traditional audio software can expose every control at once. Audixo keeps the workflow visual and progressive: begin with the source, open only the controls needed for the task, preview the result, then keep or remove that edit.</p></article><div className="ax33-about-flow"><span>01<b>Import</b><em>Bring the source</em></span><span>02<b>Shape</b><em>Work on the exact part</em></span><span>03<b>Listen</b><em>Preview before applying</em></span><span>04<b>Finish</b><em>Export or save locally</em></span></div></section>
 <section className="ax26-about-manifesto"><small>THE PRODUCT IDEA</small><h2>Power where it matters.<br/><em>Clarity everywhere else.</em></h2><p>Audixo does not try to copy a desktop DAW pixel-for-pixel. It brings the editing structures creators actually need into a browser workspace that remains readable on desktop, tablet and mobile.</p></section>
 <section className="ax26-value-grid ax33-value-grid">{values.map(([n,h,p])=><article key={n}><span>{n}</span><h3>{h}</h3><p>{p}</p><i/></article>)}</section>
 <section className="ax26-nexivo ax32-nexivo-card ax33-nexivo-teaser"><div><small>THE PARENT COMPANY</small><h2>Powered by <em>Nexivo.</em></h2><p>Nexivo is the parent company behind Audixo. Since 2025, Nexivo has worked across digital products, trading-related research, SEO and discovery systems, growth workflows and practical software experiments.</p><div className="ax32-nexivo-tags"><span>Digital products</span><span>SEO research</span><span>Trading research</span><span>Growth systems</span></div></div><Link to="/nexivo">Meet Nexivo <span>↗</span></Link></section>
 </main></SiteShell>}

export function Nexivo(){return <SiteShell><Seo title="Nexivo — Digital Products, Research & Growth Systems" description="Nexivo is the parent company behind Audixo Studio, working across digital products, trading research, SEO discovery, growth systems and software experiments." path="/nexivo"/><main className="page-shell ax26-about ax32-nexivo-page ax33-nexivo-page">
 <section className="v11-page-hero ax33-nexivo-hero"><div className="eyebrow"><span/> NEXIVO / SINCE 2025</div><h1>Build useful systems.<br/>Research what <em>moves next.</em></h1><p>Nexivo is a multi-disciplinary parent company building digital products and research-led systems across software, trading research, SEO discovery, growth operations and new product experiments.</p></section>
 <section className="ax33-nexivo-mission"><article><small>OUR MISSION</small><h2>Turn useful ideas into systems people can actually use.</h2><p>We combine product thinking, research, automation and execution to move from an idea to a practical working system.</p></article><article><small>OUR VISION</small><h2>Build a portfolio of focused digital ventures.</h2><p>Audixo is one of those ventures: a creator-first audio workspace developed inside Nexivo's broader build-and-research ecosystem.</p></article></section>
 <section className="ax32-nexivo-orbit ax33-nexivo-orbit"><div><strong>NEXIVO</strong><span>BUILD · RESEARCH · GROW</span></div><i/><i/><i/><i/></section>
 <section className="ax26-value-grid ax33-value-grid">{[['01','Digital products','Turn clear user problems into useful web products and repeatable workflows.'],['02','SEO & discovery','Research how products, content and ideas are found, understood and positioned.'],['03','Trading research','Explore market, workflow and information systems that support disciplined trading research.'],['04','Growth systems','Connect content, audiences, automation and better digital execution.'],['05','Product experiments','Prototype, test and refine ideas before treating them as finished products.'],['06','Operations','Build repeatable structures around projects so useful work can scale.']].map(([n,h,p])=><article key={n}><span>{n}</span><h3>{h}</h3><p>{p}</p><i/></article>)}</section>
 <section className="ax33-nexivo-products"><header><small>NEXIVO VENTURES</small><h2>Different problems.<br/><em>One build mindset.</em></h2></header><article><b>AUDIXO</b><span>Audio tools</span><p>Browser-based trimming, mashups, stem separation, effects and export.</p><Link to="/">Explore product ↗</Link></article><article><b>RESEARCH SYSTEMS</b><span>SEO · discovery · market research</span><p>Research-led systems that help identify opportunities, structure information and improve execution.</p></article><article><b>FUTURE BUILDS</b><span>New tools and experiments</span><p>Focused software ideas developed when a useful problem and clear workflow come together.</p></article></section>
 </main></SiteShell>}
