import { Link } from 'react-router-dom'
import type { CSSProperties } from 'react'
import Seo from '../components/Seo'
import SiteShell from '../components/SiteShell'

const featureGroups=[
 {n:'01',tag:'EDIT',title:'See the source while you shape it.',body:'The active trim sits over a faded full-source waveform, so you can always see what existed before the edit.',points:['Large start/end handles','Exact second fields','Middle selection and remove/join'],tone:'green'},
 {n:'02',tag:'SOUND',title:'Presets that explain themselves.',body:'Choose a preset to open its settings first. Nothing is applied until you review the controls and press Apply.',points:['Curated presets','Only relevant controls shown','Every applied edit removable'],tone:'pink'},
 {n:'03',tag:'LAYERS',title:'Open a mix into real source groups.',body:'Audixo separates supported stems, then gives every returned source its own mute, solo and level controls.',points:['Lyrics/Vocals · Music · Drums · Bass · Other','Studio AI when supported','Add music and beat layers'],tone:'cyan'},
 {n:'04',tag:'LIBRARY',title:'Finish it now. Find it again.',body:'Saved exports can be previewed, reopened, downloaded again or removed without an Audixo account.',points:['Local browser saves','Download again','Reopen in Studio or Vocals'],tone:'purple'},
]

export default function Features(){return <SiteShell><Seo title="Audixo Features — Trim, Mashup, Stems, Effects & Export" description="Explore Audixo trimming, adjustable presets, vocal layers, local library and export workflows." path="/features"/><main className="ax25-features ax27-features"><section className="page-shell ax25-page-hero"><div className="ax25-kicker"><i/> FEATURES / BUILT AROUND THE AUDIO</div><h1>Power where it matters.<br/><em>Clarity everywhere else.</em></h1><p>Audixo is designed to feel like one coherent studio, not a pile of unrelated mini tools.</p></section><section className="page-shell ax25-feature-showcase ax27-feature-showcase">{featureGroups.map((f,index)=><article key={f.n} className={`tone-${f.tone} ${index%2?'reverse':''} ax25-reveal-me`}><div className="ax25-feature-copy"><span>{f.n} / {f.tag}</span><h2>{f.title}</h2><p>{f.body}</p><ul>{f.points.map(p=><li key={p}>{p}</li>)}</ul></div><div className="ax25-feature-visual"><div className="ax25-feature-window ax27-feature-window"><header><i/><i/><i/><span>AUDIXO / {f.tag}</span></header><div className="ax27-feature-orb one"/><div className="ax27-feature-orb two"/><div className="ax25-feature-wave">{Array.from({length:54},(_,i)=><i key={i} style={{'--h':`${16+((i*27+index*9)%68)}%`,'--i':i} as CSSProperties}/>)}</div><div className="ax25-feature-active"/><div className="ax27-feature-playhead"/><aside><span/><span/><span/></aside></div></div></article>)}</section><section className="page-shell ax25-feature-tool-grid ax27-feature-tool-grid"><header><div className="ax25-kicker"><i/> FOCUSED TOOLS</div><h2>Small task?<br/><em>Open only what you need.</em></h2></header><div>{[['Trim Audio','/tools/trim-audio'],['Echo & Delay','/tools/echo'],['Slowed + Reverb','/tools/slowed-reverb'],['Pitch','/tools/pitch'],['8D / 16D Motion','/tools/spatial-motion'],['Vocal Layers','/tools/vocals'],['Mashup Songs','/tools/mashup']].map(([name,url],i)=><Link className="ax27-outline-card" key={name} to={url}><b>{String(i+1).padStart(2,'0')}</b><strong>{name}</strong><span>↗</span></Link>)}</div></section></main></SiteShell>}
