import { useEffect,useMemo,useState } from 'react'
import Seo from '../components/Seo'
import SiteShell from '../components/SiteShell'
import SavedMixCard from '../editor/SavedMixCard'
import { deleteLibraryMix,getLibraryMixes,libraryLimit,type LibraryMix } from '../editor/library'

export default function Library(){
 const [items,setItems]=useState<LibraryMix[]>([]),[loading,setLoading]=useState(true),[query,setQuery]=useState(''),[sort,setSort]=useState<'newest'|'oldest'|'name'>('newest')
 useEffect(()=>{let active=true;getLibraryMixes().then(rows=>{if(active)setItems(rows)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[])
 const remove=async(id:string)=>{await deleteLibraryMix(id);setItems(cur=>cur.filter(x=>x.id!==id))}
 const visible=useMemo(()=>items.filter(x=>x.name.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='name'?a.name.localeCompare(b.name):sort==='oldest'?a.createdAt-b.createdAt:b.createdAt-a.createdAt),[items,query,sort])
 const seconds=items.reduce((n,x)=>n+(x.duration||0),0),mb=items.reduce((n,x)=>n+(x.size||0),0)/1048576
 return <SiteShell><Seo title="Saved Audio Library" description="Preview, download and reopen Audixo exports saved locally in your browser." path="/library"/><main className="page-shell ax25-library"><section className="ax25-page-hero library"><div><div className="ax25-kicker"><i/> YOUR LOCAL LIBRARY</div><h1>Finished takes.<br/><em>Ready when you are.</em></h1><p>Preview, reopen, download again or remove up to {libraryLimit} finished exports from this browser profile.</p></div><div className="ax25-library-disc" aria-hidden="true"><i/><b>{items.length}</b><span>SAVED</span></div></section><section className="ax25-library-stats"><article><small>SLOTS</small><strong>{items.length}<span> / {libraryLimit}</span></strong><p>Saved mixes in this browser.</p></article><article><small>DURATION</small><strong>{Math.round(seconds/60)}<span> min</span></strong><p>Approximate total playable audio.</p></article><article><small>STORAGE</small><strong>{mb<10?mb.toFixed(1):Math.round(mb)}<span> MB</span></strong><p>Local browser storage, not cloud backup.</p></article></section><section className="ax25-library-toolbar"><label><span>Find a mix</span><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search saved audio…"/></label><label><span>Sort</span><select value={sort} onChange={e=>setSort(e.target.value as typeof sort)}><option value="newest">Newest first</option><option value="oldest">Oldest first</option><option value="name">Name A–Z</option></select></label><div><b>{visible.length}</b><span>shown</span></div></section><section className="ax25-library-grid">{loading?<div className="ax25-empty-state"><strong>Loading your Library…</strong></div>:visible.length?visible.map(item=><SavedMixCard key={item.id} item={item} onDelete={remove}/>):<div className="ax25-empty-state"><strong>{items.length?'No mix matches that search.':'Your Library is empty.'}</strong><p>{items.length?'Try another title.':'Export from the Studio and enable Save to browser library.'}</p></div>}</section></main></SiteShell>
}
