import { useEffect,useMemo,useRef,useState } from 'react'
import type { CSSProperties,PointerEvent as ReactPointerEvent } from 'react'
import Seo from '../components/Seo'
import SiteShell from '../components/SiteShell'
import { decodeAudio } from '../editor/audioEngine'
import { downloadBlob,encodeMp3,encodeWav } from '../editor/encoder'
import { getLibraryMixes,saveMixToLibrary,type LibraryMix } from '../editor/library'
import { formatTime } from '../editor/utils'

type Fx={gainDb:number;pan:number;speed:number;pitch:number;fadeIn:number;fadeOut:number;bass:number;mid:number;treble:number;echo:number;reverb:number;motion:number;reverse:boolean}
type Clip={id:string;trackId:string;name:string;startAt:number;trimStart:number;trimEnd:number;preset:string;fx:Fx}
type Track={id:string;name:string;blob:Blob;buffer:AudioBuffer;clips:Clip[];muted:boolean;solo:boolean;gainDb:number}
type DragState={clipId:string;mode:'move'|'left'|'right';x:number;startAt:number;trimStart:number;trimEnd:number;speed:number}|null

const cleanFx:Fx={gainDb:0,pan:0,speed:1,pitch:0,fadeIn:.18,fadeOut:.22,bass:0,mid:0,treble:0,echo:0,reverb:0,motion:0,reverse:false}
const presets=[
 {id:'clean',name:'Clean section',fx:{...cleanFx}},
 {id:'cross',name:'Smooth crossfade',fx:{...cleanFx,fadeIn:1.2,fadeOut:1.2}},
 {id:'vocal',name:'Lead vocal',fx:{...cleanFx,gainDb:1.5,bass:-1,mid:1.5,treble:1,reverb:9}},
 {id:'bed',name:'Music bed',fx:{...cleanFx,gainDb:-6,bass:1.5,mid:-1,treble:.5,fadeIn:.7,fadeOut:1.1}},
 {id:'lofi',name:'Lo-fi texture',fx:{...cleanFx,gainDb:-1,bass:2,mid:-2,treble:-4,echo:7,reverb:12}},
 {id:'space',name:'Wide space',fx:{...cleanFx,pan:.12,echo:16,reverb:24,motion:26,fadeIn:.45,fadeOut:.55}},
 {id:'punch',name:'Punchy transition',fx:{...cleanFx,gainDb:1,bass:2.5,mid:1,treble:1.5,fadeIn:.08,fadeOut:.18}},
]

const uid=(prefix='m')=>`${prefix}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,8)}`
const db=(v:number)=>Math.pow(10,v/20)
const clipLength=(clip:Clip)=>Math.max(.02,(clip.trimEnd-clip.trimStart)/Math.max(.25,clip.fx.speed)*Math.pow(2,-clip.fx.pitch/12))
const clipEnd=(clip:Clip)=>clip.startAt+clipLength(clip)

function peaks(track:Track,clip:Clip,count=180){
 const data=track.buffer.getChannelData(0),rate=track.buffer.sampleRate,start=Math.max(0,Math.floor(clip.trimStart*rate)),end=Math.min(data.length,Math.ceil(clip.trimEnd*rate)),span=Math.max(1,end-start),out:number[]=[]
 for(let i=0;i<count;i++){const a=start+Math.floor(span*i/count),b=Math.min(end,start+Math.floor(span*(i+1)/count));let peak=.02;const step=Math.max(1,Math.floor((b-a)/16));for(let j=a;j<b;j+=step)peak=Math.max(peak,Math.abs(data[j]||0));out.push(Math.min(1,peak))}
 return out
}
function phraseGuides(track:Track,clip:Clip){
 const data=track.buffer.getChannelData(0),rate=track.buffer.sampleRate,from=Math.floor(clip.trimStart*rate),to=Math.floor(clip.trimEnd*rate),window=Math.max(256,Math.floor(rate*.065)),values:{t:number;e:number}[]=[]
 for(let p=from;p<to;p+=window){let sum=0,n=0;for(let i=p;i<Math.min(to,p+window);i+=12){const v=data[i]||0;sum+=v*v;n++}values.push({t:(p-from)/rate,e:Math.sqrt(sum/Math.max(1,n))})}
 if(values.length<4)return [] as number[]
 const ordered=values.map(v=>v.e).sort((a,b)=>a-b),threshold=ordered[Math.floor(ordered.length*.26)]||0,markers:number[]=[];let last=-2
 for(let i=1;i<values.length-1;i++){const v=values[i];if(v.e<=threshold&&v.e<=values[i-1].e&&v.e<=values[i+1].e&&v.t-last>.42){markers.push(v.t);last=v.t;if(markers.length>=18)break}}
 return markers
}
function impulse(ctx:OfflineAudioContext,seconds=1.7,decay=2.4){const len=Math.max(1,Math.floor(ctx.sampleRate*seconds)),buf=ctx.createBuffer(2,len,ctx.sampleRate);for(let c=0;c<2;c++){const d=buf.getChannelData(c);let seed=97+c*31;for(let i=0;i<len;i++){seed=(seed*16807)%2147483647;const noise=(seed/2147483647)*2-1;d[i]=noise*Math.pow(1-i/len,decay)}}return buf}
function reverseSlice(buffer:AudioBuffer,start:number,end:number){const rate=buffer.sampleRate,from=Math.max(0,Math.floor(start*rate)),to=Math.min(buffer.length,Math.ceil(end*rate)),len=Math.max(1,to-from),out=new AudioBuffer({numberOfChannels:buffer.numberOfChannels,length:len,sampleRate:rate});for(let c=0;c<buffer.numberOfChannels;c++){const src=buffer.getChannelData(c),dst=out.getChannelData(c);for(let i=0;i<len;i++)dst[i]=src[to-1-i]||0}return out}
async function renderMix(tracks:Track[]){
 const hasSolo=tracks.some(t=>t.solo),clips=tracks.filter(t=>!t.muted&&(!hasSolo||t.solo)).flatMap(t=>t.clips.map(c=>({track:t,clip:c})));if(!clips.length)throw new Error('Add at least one section to the mashup.')
 const rate=44100,lengthSeconds=Math.max(.1,...clips.map(x=>clipEnd(x.clip))),offline=new OfflineAudioContext(2,Math.ceil(lengthSeconds*rate),rate),verbImpulse=impulse(offline)
 for(const {track,clip} of clips){
  const source=offline.createBufferSource(),playBuffer=clip.fx.reverse?reverseSlice(track.buffer,clip.trimStart,clip.trimEnd):track.buffer;source.buffer=playBuffer;source.playbackRate.value=Math.max(.25,clip.fx.speed);source.detune.value=clip.fx.pitch*100
  const low=offline.createBiquadFilter();low.type='lowshelf';low.frequency.value=170;low.gain.value=clip.fx.bass
  const mid=offline.createBiquadFilter();mid.type='peaking';mid.frequency.value=1100;mid.Q.value=.8;mid.gain.value=clip.fx.mid
  const high=offline.createBiquadFilter();high.type='highshelf';high.frequency.value=4800;high.gain.value=clip.fx.treble
  const pan=offline.createStereoPanner(),basePan=Math.max(-1,Math.min(1,clip.fx.pan));pan.pan.value=basePan
  const gain=offline.createGain(),base=db(clip.fx.gainDb+track.gainDb),start=Math.max(0,clip.startAt),duration=clipLength(clip),fi=Math.min(clip.fx.fadeIn,duration/2),fo=Math.min(clip.fx.fadeOut,duration/2)
  gain.gain.setValueAtTime(fi>0?0:base,start);if(fi>0)gain.gain.linearRampToValueAtTime(base,start+fi);if(fo>0){gain.gain.setValueAtTime(base,Math.max(start+fi,start+duration-fo));gain.gain.linearRampToValueAtTime(0,start+duration)}if(clip.fx.motion>0){const depth=Math.min(.92,clip.fx.motion/100*.82),hz=.12+clip.fx.motion/100*.52,step=.08;for(let t=0;t<=duration;t+=step)pan.pan.setValueAtTime(Math.max(-1,Math.min(1,basePan+Math.sin(t*Math.PI*2*hz)*depth)),start+t)}
  source.connect(low).connect(mid).connect(high).connect(pan);pan.connect(gain)
  if(clip.fx.echo>0){const delay=offline.createDelay(1.2),feedback=offline.createGain(),wet=offline.createGain();delay.delayTime.value=.22+clip.fx.echo/100*.38;feedback.gain.value=Math.min(.58,.08+clip.fx.echo/100*.46);wet.gain.value=Math.min(.55,clip.fx.echo/100*.5);pan.connect(delay);delay.connect(feedback);feedback.connect(delay);delay.connect(wet).connect(gain)}
  if(clip.fx.reverb>0){const convolver=offline.createConvolver(),wet=offline.createGain();convolver.buffer=verbImpulse;wet.gain.value=Math.min(.62,clip.fx.reverb/100*.58);pan.connect(convolver).connect(wet).connect(gain)}
  gain.connect(offline.destination);source.start(start,clip.fx.reverse?0:Math.max(0,clip.trimStart),Math.max(.02,clip.trimEnd-clip.trimStart))
 }
 return offline.startRendering()
}

export default function MashupTool(){
 const input=useRef<HTMLInputElement|null>(null),timelineInner=useRef<HTMLDivElement|null>(null),drag=useRef<DragState>(null)
 const [tracks,setTracks]=useState<Track[]>([]),[selected,setSelected]=useState<string|null>(null),[playhead,setPlayhead]=useState(0),[zoom,setZoom]=useState(1),[busy,setBusy]=useState(''),[message,setMessage]=useState(''),[previewUrl,setPreviewUrl]=useState(''),[format,setFormat]=useState<'mp3'|'wav'>('mp3'),[kbps,setKbps]=useState(320),[libraryOpen,setLibraryOpen]=useState(false),[library,setLibrary]=useState<LibraryMix[]>([]),[editTool,setEditTool]=useState<'move'|'razor'>('move'),[fxScope,setFxScope]=useState<'clip'|'track'|'mix'>('clip')
 const allClips=useMemo(()=>tracks.flatMap(t=>t.clips),[tracks]),contentDuration=useMemo(()=>Math.max(30,...allClips.map(clipEnd)),[allClips]),timelineDuration=Math.max(30,Math.ceil(contentDuration/30)*30),selectedPair=useMemo(()=>{for(const t of tracks){const c=t.clips.find(x=>x.id===selected);if(c)return {track:t,clip:c}}return null},[tracks,selected])
 useEffect(()=>()=>{if(previewUrl)URL.revokeObjectURL(previewUrl)},[previewUrl])
 useEffect(()=>{const move=(e:PointerEvent)=>{const d=drag.current,el=timelineInner.current;if(!d||!el)return;const rect=el.getBoundingClientRect(),delta=(e.clientX-d.x)/Math.max(1,rect.width)*timelineDuration;setTracks(old=>old.map(t=>({...t,clips:t.clips.map(c=>{if(c.id!==d.clipId)return c;if(d.mode==='move')return {...c,startAt:Math.max(0,d.startAt+delta)};if(d.mode==='left'){const sourceDelta=delta*d.speed,nextTrim=Math.max(0,Math.min(d.trimEnd-.04,d.trimStart+sourceDelta)),timelineDelta=(nextTrim-d.trimStart)/d.speed;return {...c,trimStart:nextTrim,startAt:Math.max(0,d.startAt+timelineDelta)}}const sourceDelta=delta*d.speed;return {...c,trimEnd:Math.max(d.trimStart+.04,d.trimEnd+sourceDelta)}})})))};const up=()=>{drag.current=null;document.body.classList.remove('ax29-dragging')};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up);return()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up)}},[timelineDuration])
 const patchClip=(clipId:string,patch:Partial<Clip>|((clip:Clip)=>Clip))=>setTracks(v=>v.map(t=>({...t,clips:t.clips.map(c=>c.id===clipId?(typeof patch==='function'?patch(c):{...c,...patch}):c)})))
 const patchFx=(clipId:string,patch:Partial<Fx>)=>{if(fxScope==='mix'){setTracks(v=>v.map(t=>({...t,clips:t.clips.map(c=>({...c,fx:{...c.fx,...patch}}))})));return}if(fxScope==='track'&&selectedPair){setTracks(v=>v.map(t=>t.id===selectedPair.track.id?{...t,clips:t.clips.map(c=>({...c,fx:{...c.fx,...patch}}))}:t));return}patchClip(clipId,c=>({...c,fx:{...c.fx,...patch}}))}
 const patchTrack=(trackId:string,patch:Partial<Pick<Track,'muted'|'solo'|'gainDb'>>)=>setTracks(v=>v.map(t=>t.id===trackId?{...t,...patch}:t))
 const addBlob=async(blob:Blob,name:string)=>{setBusy('Reading audio...');setMessage('');try{const buffer=await decodeAudio(await blob.arrayBuffer()),trackId=uid('track'),clipId=uid('clip'),startAt=allClips.length?Math.max(0,Math.max(...allClips.map(clipEnd))-.35):0;const clip:Clip={id:clipId,trackId,name,startAt,trimStart:0,trimEnd:buffer.duration,preset:'clean',fx:{...cleanFx}};setTracks(v=>[...v,{id:trackId,name,blob,buffer,clips:[clip],muted:false,solo:false,gainDb:0}]);setSelected(clipId);setPlayhead(startAt)}catch(e){setMessage(e instanceof Error?e.message:'Audio could not be decoded.')}finally{setBusy('')}}
 const addFiles=async(files:FileList|null)=>{if(!files)return;for(const file of Array.from(files).slice(0,8))await addBlob(file,file.name)}
 const selectPreset=(id:string)=>{if(!selectedPair)return;const p=presets.find(x=>x.id===id);if(!p)return;if(fxScope==='mix'){setTracks(v=>v.map(t=>({...t,clips:t.clips.map(c=>({...c,preset:id,fx:{...p.fx}}))})));return}if(fxScope==='track'){setTracks(v=>v.map(t=>t.id===selectedPair.track.id?{...t,clips:t.clips.map(c=>({...c,preset:id,fx:{...p.fx}}))}:t));return}patchClip(selectedPair.clip.id,c=>({...c,preset:id,fx:{...p.fx}}))}
 const splitSelectedByBoundaries=(boundaries:number[])=>{if(!selectedPair)return;const {track,clip}=selectedPair;const clean=[clip.trimStart,...boundaries.filter(v=>v>clip.trimStart+.03&&v<clip.trimEnd-.03),clip.trimEnd].sort((a,b)=>a-b);if(clean.length<3){setMessage('No useful split points were found inside this section.');return}const rate=Math.max(.25,clip.fx.speed)*Math.pow(2,-clip.fx.pitch/12);let cursor=clip.startAt;const pieces:Clip[]=[];for(let i=0;i<clean.length-1;i++){const a=clean[i],b=clean[i+1];if(b-a<.04)continue;const piece={...clip,id:uid('clip'),name:`${clip.name} · ${String(i+1).padStart(2,'0')}`,startAt:cursor,trimStart:a,trimEnd:b,fx:{...clip.fx}};pieces.push(piece);cursor+=Math.max(.02,(b-a)/Math.max(.25,clip.fx.speed)*Math.pow(2,-clip.fx.pitch/12))}setTracks(v=>v.map(t=>t.id===track.id?{...t,clips:t.clips.flatMap(c=>c.id===clip.id?pieces:[c])}:t));setSelected(pieces[0]?.id||null);setMessage(`${pieces.length} precise sections created. Each section now has its own effects and timeline position.`)}
 const splitEvery=(seconds:number)=>{if(!selectedPair)return;const {clip}=selectedPair,sourceStep=seconds*Math.max(.25,clip.fx.speed)*Math.pow(2,clip.fx.pitch/12),cuts:number[]=[];for(let t=clip.trimStart+sourceStep;t<clip.trimEnd-.03;t+=sourceStep)cuts.push(t);splitSelectedByBoundaries(cuts)}
 const splitAtPhraseGuides=()=>{if(!selectedPair)return;const guides=phraseGuides(selectedPair.track,selectedPair.clip).map(v=>selectedPair.clip.trimStart+v);splitSelectedByBoundaries(guides)}
 const nudgeSelected=(seconds:number)=>{if(!selectedPair)return;patchClip(selectedPair.clip.id,{startAt:Math.max(0,selectedPair.clip.startAt+seconds)})}
 const duplicate=()=>{if(!selectedPair)return;const {track,clip}=selectedPair,newClip={...clip,id:uid('clip'),name:`${clip.name} · copy`,startAt:clipEnd(clip)+.08,fx:{...clip.fx}};setTracks(v=>v.map(t=>t.id===track.id?{...t,clips:[...t.clips,newClip]}:t));setSelected(newClip.id)}
 const splitAtPlayhead=()=>{if(!selectedPair)return;const {track,clip}=selectedPair,end=clipEnd(clip);if(playhead<=clip.startAt+.03||playhead>=end-.03){setMessage('Move the playhead inside the selected section before splitting.');return}const sourcePoint=clip.trimStart+(playhead-clip.startAt)*clip.fx.speed*Math.pow(2,clip.fx.pitch/12),left:Clip={...clip,trimEnd:sourcePoint,fx:{...clip.fx}},right:Clip={...clip,id:uid('clip'),name:`${clip.name} · next`,startAt:playhead,trimStart:sourcePoint,fx:{...clip.fx}};setTracks(v=>v.map(t=>t.id===track.id?{...t,clips:t.clips.flatMap(c=>c.id===clip.id?[left,right]:[c])}:t));setSelected(right.id);setMessage('Section split at the playhead. Both pieces remain independently editable.')}
 const removeSelected=()=>{if(!selectedPair)return;const id=selectedPair.clip.id;setTracks(v=>v.map(t=>({...t,clips:t.clips.filter(c=>c.id!==id)})).filter(t=>t.clips.length));setSelected(null)}

 const splitClipAtPointer=(e:ReactPointerEvent,clip:Clip)=>{e.preventDefault();e.stopPropagation();const el=e.currentTarget as HTMLElement,r=el.getBoundingClientRect(),ratio=Math.max(0,Math.min(1,(e.clientX-r.left)/Math.max(1,r.width))),sourcePoint=clip.trimStart+(clip.trimEnd-clip.trimStart)*ratio,end=clipEnd(clip),timelinePoint=clip.startAt+(end-clip.startAt)*ratio;if(sourcePoint<=clip.trimStart+.025||sourcePoint>=clip.trimEnd-.025)return;const track=tracks.find(t=>t.id===clip.trackId);if(!track)return;const left:Clip={...clip,trimEnd:sourcePoint,fx:{...clip.fx}},right:Clip={...clip,id:uid('clip'),name:`${clip.name} · split`,startAt:timelinePoint,trimStart:sourcePoint,fx:{...clip.fx}};setTracks(v=>v.map(t=>t.id===track.id?{...t,clips:t.clips.flatMap(c=>c.id===clip.id?[left,right]:[c])}:t));setSelected(right.id);setPlayhead(timelinePoint);setMessage('Razor split created. Each new section can be moved, trimmed and processed independently.')}
 const beginDrag=(e:ReactPointerEvent,clip:Clip,mode:'move'|'left'|'right')=>{e.preventDefault();e.stopPropagation();drag.current={clipId:clip.id,mode,x:e.clientX,startAt:clip.startAt,trimStart:clip.trimStart,trimEnd:clip.trimEnd,speed:clip.fx.speed*Math.pow(2,clip.fx.pitch/12)};document.body.classList.add('ax29-dragging');setSelected(clip.id)}
 const previewSection=async()=>{if(!selectedPair||busy)return;setBusy('Rendering section...');setMessage('');try{const only={...selectedPair.track,clips:[{...selectedPair.clip,startAt:0}]};const buffer=await renderMix([only]);const blob=encodeWav(buffer);if(previewUrl)URL.revokeObjectURL(previewUrl);setPreviewUrl(URL.createObjectURL(blob));setMessage('Selected section rendered. Listen below before placing or styling it again.')}catch(e){setMessage(e instanceof Error?e.message:'Section preview failed.')}finally{setBusy('')}}
 const preview=async()=>{setBusy('Building preview...');setMessage('');try{const rendered=await renderMix(tracks),blob=encodeWav(rendered);if(previewUrl)URL.revokeObjectURL(previewUrl);setPreviewUrl(URL.createObjectURL(blob));setMessage('Preview ready. Listen while you refine the sections, then export when the transitions feel right.')}catch(e){setMessage(e instanceof Error?e.message:'Preview failed.')}finally{setBusy('')}}
 const exportMix=async()=>{setBusy('Rendering mashup...');setMessage('');try{const rendered=await renderMix(tracks),blob=format==='mp3'?await encodeMp3(rendered,kbps):encodeWav(rendered),name=`audixo-mashup.${format}`;downloadBlob(blob,name);await saveMixToLibrary({name:'Audixo Mashup',blob,format,kbps,duration:rendered.duration});setMessage('Mashup downloaded and saved to your local Library.')}catch(e){setMessage(e instanceof Error?e.message:'Mashup export failed.')}finally{setBusy('')}}
 const openLibrary=async()=>{setLibrary(await getLibraryMixes());setLibraryOpen(true)}
 return <SiteShell><Seo title="Audixo Mashup Studio — Multitrack Song & Verse Editor" description="Build a layer-by-layer mashup with draggable audio sections, split points, per-section effects, crossfades, preview and export." path="/tools/mashup"/><main className="page-shell ax29-mashup-page">
  <section className="ax25-page-hero ax29-mashup-hero"><div className="ax25-kicker"><i/> TOOLS / MASHUP</div><h1>Break the song into moments.<br/><em>Build the mashup your way.</em></h1><p>A browser multitrack workspace built around the editing structure that matters: thin source lanes, movable clips, unlimited split points, clip-level effects, track-level shaping and whole-mix control.</p></section>
  <section className="ax29-mashup-shell">
   <header className="ax29-mashup-head"><div><small>MULTITRACK ARRANGEMENT</small><strong>{tracks.length} source lanes · {allClips.length} clips · {formatTime(contentDuration,true)}</strong><p>Split a verse, move that clip anywhere in time, trim its edges, then apply effects to one clip, one source track or the entire mashup.</p></div><div><button onClick={()=>input.current?.click()}>+ Add audio</button><button onClick={openLibrary}>From Library</button></div></header>
   <input ref={input} hidden multiple type="file" accept="audio/*,.mp3,.wav,.m4a,.aac,.ogg,.flac" onChange={e=>{addFiles(e.target.files);e.target.value=''}}/>
   {!allClips.length?<button className="ax29-mashup-empty" onClick={()=>input.current?.click()}><span><i/><i/><i/><b>M</b></span><strong>Start with two sounds.</strong><p>Upload songs, vocals, music beds or instrumentals. Every source becomes its own editable lane.</p><em>UPLOAD · SPLIT · MOVE · SHAPE · EXPORT</em></button>:<>
    <div className="ax29-mashup-toolbar ax30-mashup-toolbar ax32-mashup-toolbar"><div className="ax32-tool-mode"><button className={editTool==='move'?'active':''} onClick={()=>setEditTool('move')}>Move tool</button><button className={editTool==='razor'?'active':''} onClick={()=>setEditTool('razor')}>Razor tool</button></div><div><button onClick={splitAtPlayhead} disabled={!selectedPair}>Split at playhead</button><button onClick={()=>splitEvery(1)} disabled={!selectedPair}>1-sec cuts</button><button onClick={()=>splitEvery(5)} disabled={!selectedPair}>5-sec cuts</button><button onClick={()=>splitEvery(10)} disabled={!selectedPair}>10-sec cuts</button><button onClick={splitAtPhraseGuides} disabled={!selectedPair}>Auto verse cuts</button><button onClick={()=>nudgeSelected(-.1)} disabled={!selectedPair}>−0.1s</button><button onClick={()=>nudgeSelected(.1)} disabled={!selectedPair}>+0.1s</button><button onClick={duplicate} disabled={!selectedPair}>Duplicate</button><button onClick={removeSelected} disabled={!selectedPair}>Remove</button></div><label>Fine zoom <input type="range" min="1" max="12" step=".1" value={zoom} onChange={e=>setZoom(Number(e.target.value))}/><b>{zoom.toFixed(1)}×</b><button type="button" className="ax38-fit-zoom" onClick={()=>{setZoom(1);timelineInner.current?.parentElement?.scrollTo({left:0,behavior:'smooth'})}}>Fit</button></label></div>
    <div className="ax29-mashup-workspace">
     <section className="ax29-arrangement"><div className="ax29-arrangement-scroll"><div ref={timelineInner} className="ax29-arrangement-inner" style={{width:`${zoom*100}%`} as CSSProperties} onPointerDown={e=>{const r=e.currentTarget.getBoundingClientRect();setPlayhead(Math.max(0,Math.min(timelineDuration,(e.clientX-r.left)/r.width*timelineDuration)))}}>
      <div className="ax29-ruler">{Array.from({length:13},(_,i)=><span key={i} style={{left:`${i/12*100}%`}}>{formatTime(timelineDuration*i/12)}</span>)}<i className="ax29-playhead" style={{left:`${Math.min(100,playhead/timelineDuration*100)}%`}}><b>{formatTime(playhead,true)}</b></i></div>
      {tracks.map((track,ti)=><div className="ax29-track" key={track.id}><aside><span>{String(ti+1).padStart(2,'0')}</span><strong>{track.name}</strong><small>{track.clips.length} section{track.clips.length===1?'':'s'}</small><div className="ax30-track-buttons"><button className={track.muted?'active':''} onClick={e=>{e.stopPropagation();patchTrack(track.id,{muted:!track.muted})}}>M</button><button className={track.solo?'active':''} onClick={e=>{e.stopPropagation();patchTrack(track.id,{solo:!track.solo})}}>S</button></div><input aria-label={`${track.name} level`} type="range" min="-18" max="6" step=".5" value={track.gainDb} onChange={e=>patchTrack(track.id,{gainDb:Number(e.target.value)})}/></aside><div className="ax29-track-lane">{track.clips.map(clip=>{const left=clip.startAt/timelineDuration*100,width=clipLength(clip)/timelineDuration*100,guides=phraseGuides(track,clip);return <div key={clip.id} className={`ax29-clip ${selected===clip.id?'selected':''}`} style={{left:`${left}%`,width:`${Math.max(.9,width)}%`,'--clip-color':ti%4} as CSSProperties} onPointerDown={e=>editTool==='razor'?splitClipAtPointer(e,clip):beginDrag(e,clip,'move')} onClick={e=>{e.stopPropagation();setSelected(clip.id);if(editTool==='move')setPlayhead(clip.startAt)}}><button className="ax29-trim-handle left" aria-label="Trim section start" onPointerDown={e=>beginDrag(e,clip,'left')}/><span className="ax29-clip-wave">{peaks(track,clip).map((v,i)=><i key={i} style={{height:`${Math.max(6,v*90)}%`}}/>)}</span>{guides.map((g,i)=><i className="ax29-phrase-guide" key={i} style={{left:`${g/Math.max(.01,clip.trimEnd-clip.trimStart)*100}%`}}/>)}<span className="ax29-fade left" style={{width:`${Math.min(45,clip.fx.fadeIn/Math.max(.01,clipLength(clip))*100)}%`}}/><span className="ax29-fade right" style={{width:`${Math.min(45,clip.fx.fadeOut/Math.max(.01,clipLength(clip))*100)}%`}}/><b>{clip.name}</b><em>{formatTime(clip.trimStart)} → {formatTime(clip.trimEnd)}</em><button className="ax29-trim-handle right" aria-label="Trim section end" onPointerDown={e=>beginDrag(e,clip,'right')}/></div>})}</div></div>)}
     </div></div><p className="ax29-arrangement-note">Pointer mode lets you grab any clip and move it left or right. Razor, the playhead and 1/5/10-second cuts create independent clips. Drag either edge to trim. The scope switch in the inspector chooses whether an effect targets this clip, its source track or the entire mashup.</p></section>
     <aside className="ax29-mashup-inspector ax32-mashup-inspector">{selectedPair?<><header><small>SELECTED SECTION</small><h2>{selectedPair.clip.name}</h2><p>{selectedPair.track.name}</p><div className="ax32-fx-scope ax33-fx-scope"><button className={fxScope==='clip'?'active':''} onClick={()=>setFxScope('clip')}>This clip</button><button className={fxScope==='track'?'active':''} onClick={()=>setFxScope('track')}>Source track</button><button className={fxScope==='mix'?'active':''} onClick={()=>setFxScope('mix')}>Entire mashup</button></div></header><div className="ax29-preset-grid">{presets.map(p=><button key={p.id} className={selectedPair.clip.preset===p.id?'active':''} onClick={()=>selectPreset(p.id)}>{p.name}</button>)}</div><div className="ax29-inspector-scroll">
      <label>Start in mix <input type="number" step=".05" min="0" value={selectedPair.clip.startAt.toFixed(2)} onChange={e=>patchClip(selectedPair.clip.id,{startAt:Math.max(0,Number(e.target.value)||0)})}/></label><div className="ax29-two"><label>Trim start <input type="number" step=".01" min="0" value={selectedPair.clip.trimStart.toFixed(2)} onChange={e=>patchClip(selectedPair.clip.id,{trimStart:Math.max(0,Math.min(selectedPair.clip.trimEnd-.03,Number(e.target.value)||0))})}/></label><label>Trim end <input type="number" step=".01" min={selectedPair.clip.trimStart+.03} max={selectedPair.track.buffer.duration} value={selectedPair.clip.trimEnd.toFixed(2)} onChange={e=>patchClip(selectedPair.clip.id,{trimEnd:Math.min(selectedPair.track.buffer.duration,Math.max(selectedPair.clip.trimStart+.03,Number(e.target.value)||selectedPair.clip.trimEnd))})}/></label></div>
      <Slider title="Level" value={selectedPair.clip.fx.gainDb} min={-18} max={8} step={.5} suffix=" dB" onChange={v=>patchFx(selectedPair.clip.id,{gainDb:v})}/><Slider title="Pan" value={selectedPair.clip.fx.pan} min={-1} max={1} step={.05} onChange={v=>patchFx(selectedPair.clip.id,{pan:v})}/><Slider title="Speed" value={selectedPair.clip.fx.speed} min={.5} max={1.5} step={.01} suffix="×" onChange={v=>patchFx(selectedPair.clip.id,{speed:v})}/><Slider title="Tape pitch" value={selectedPair.clip.fx.pitch} min={-6} max={6} step={1} suffix=" st" onChange={v=>patchFx(selectedPair.clip.id,{pitch:v})}/><button type="button" className={`ax30-reverse-clip ${selectedPair.clip.fx.reverse?'active':''}`} onClick={()=>patchFx(selectedPair.clip.id,{reverse:!selectedPair.clip.fx.reverse})}><span>Reverse section</span><b>{selectedPair.clip.fx.reverse?'ON':'OFF'}</b></button><Slider title="Stereo motion" value={selectedPair.clip.fx.motion} min={0} max={100} step={1} suffix="%" onChange={v=>patchFx(selectedPair.clip.id,{motion:v})}/><div className="ax29-two"><Slider title="Fade in" value={selectedPair.clip.fx.fadeIn} min={0} max={4} step={.05} suffix=" s" onChange={v=>patchFx(selectedPair.clip.id,{fadeIn:v})}/><Slider title="Fade out" value={selectedPair.clip.fx.fadeOut} min={0} max={4} step={.05} suffix=" s" onChange={v=>patchFx(selectedPair.clip.id,{fadeOut:v})}/></div><div className="ax29-two"><Slider title="Bass" value={selectedPair.clip.fx.bass} min={-9} max={9} step={.5} suffix=" dB" onChange={v=>patchFx(selectedPair.clip.id,{bass:v})}/><Slider title="Mid" value={selectedPair.clip.fx.mid} min={-9} max={9} step={.5} suffix=" dB" onChange={v=>patchFx(selectedPair.clip.id,{mid:v})}/></div><div className="ax29-two"><Slider title="Treble" value={selectedPair.clip.fx.treble} min={-9} max={9} step={.5} suffix=" dB" onChange={v=>patchFx(selectedPair.clip.id,{treble:v})}/><Slider title="Echo" value={selectedPair.clip.fx.echo} min={0} max={100} step={1} suffix="%" onChange={v=>patchFx(selectedPair.clip.id,{echo:v})}/></div><Slider title="Reverb" value={selectedPair.clip.fx.reverb} min={0} max={100} step={1} suffix="%" onChange={v=>patchFx(selectedPair.clip.id,{reverb:v})}/></div><footer><button onClick={splitAtPlayhead}>Split here</button><button onClick={previewSection}>Preview section</button><button onClick={preview}>Preview mix</button></footer></>:<div className="ax29-inspector-empty"><b>∿</b><strong>Select a section</strong><p>Then shape only that verse, hook, music bed or transition.</p></div>}</aside>
    </div>
    <section className="ax29-mashup-export"><div><label>Format<select value={format} onChange={e=>setFormat(e.target.value as 'mp3'|'wav')}><option value="mp3">MP3</option><option value="wav">WAV</option></select></label>{format==='mp3'&&<label>Quality<select value={kbps} onChange={e=>setKbps(Number(e.target.value))}>{[128,192,256,320].map(k=><option key={k} value={k}>{k} kbps</option>)}</select></label>}</div><div><button onClick={preview} disabled={!!busy}>{busy||'Preview mashup'}</button><button className="primary" onClick={exportMix} disabled={!!busy||!allClips.length}>Download mashup</button></div></section>{previewUrl&&<section className="ax29-mashup-preview"><span>RENDERED PREVIEW</span><audio src={previewUrl} controls/></section>}{message&&<div className="ax29-mashup-message" role="status">{message}</div>}</>}
  </section>
  {libraryOpen&&<div className="ax28-library-picker" onPointerDown={e=>{if(e.target===e.currentTarget)setLibraryOpen(false)}}><section><header><div><small>LOCAL LIBRARY</small><strong>Add a saved mix as a new track</strong></div><button onClick={()=>setLibraryOpen(false)}>×</button></header><div>{library.length?library.map(m=><button key={m.id} onClick={()=>{addBlob(m.blob,`${m.name}.${m.format}`);setLibraryOpen(false)}}><span>♫</span><strong>{m.name}</strong><small>{formatTime(m.duration,true)}</small></button>):<p>No saved mixes are available in this browser yet.</p>}</div></section></div>}
 </main></SiteShell>
}

function Slider({title,value,min,max,step,suffix='',onChange}:{title:string;value:number;min:number;max:number;step:number;suffix?:string;onChange:(v:number)=>void}){return <label className="ax29-slider"><span><b>{title}</b><em>{Number(value).toFixed(step<1?2:0)}{suffix}</em></span><input type="range" min={min} max={max} step={step} value={value} onChange={e=>onChange(Number(e.target.value))}/></label>}
