import { useEffect,useMemo,useRef,useState,type CSSProperties } from 'react'
import { useLocation } from 'react-router-dom'
import Seo from '../components/Seo'
import SiteShell from '../components/SiteShell'
import AudioStudio,{type InitialAudio} from '../editor/AudioStudio'
import LibraryDrawer from '../editor/LibraryDrawer'
import { getLibraryMixes,type LibraryMix } from '../editor/library'
import { separateLocally,type LocalStem,type StemProgress } from '../services/localStems'
import { localMetadata } from '../services/media'
import { createSoundBankClip,soundBank,type SoundBankItem } from '../services/soundBank'

export default function Vocals(){
 const [file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[status,setStatus]=useState<StemProgress|null>(null),[message,setMessage]=useState(''),[stems,setStems]=useState<LocalStem[]>([]),[initial,setInitial]=useState<InitialAudio[]>([]),[library,setLibrary]=useState(false),[version,setVersion]=useState(0),[elapsed,setElapsed]=useState(0),[bankFamily,setBankFamily]=useState('All'),[bankBusy,setBankBusy]=useState(''),[mode,setMode]=useState<'studio'|'fast'>('studio'),[mix,setMix]=useState<'blend'|'voice'|'instrumental'>('blend')
 const input=useRef<HTMLInputElement>(null),abort=useRef<AbortController|null>(null),preview=useRef<HTMLAudioElement|null>(null),location=useLocation(),webGpu=typeof navigator!=='undefined'&&Boolean((navigator as any).gpu),threaded=typeof crossOriginIsolated!=='undefined'&&crossOriginIsolated
 const choose=(next:File)=>{setFile(next);setStems([]);setInitial([]);setStatus(null);setMessage('')},useMix=(mix:LibraryMix)=>{choose(new File([mix.blob],`${mix.name}.${mix.format}`,{type:mix.blob.type}));setLibrary(false)}
 useEffect(()=>{const id=(location.state as any)?.libraryId;if(id)getLibraryMixes().then(mixes=>{const item=mixes.find(m=>m.id===id);if(item)useMix(item);else setMessage('That saved mix is no longer in this browser.')});return()=>{abort.current?.abort();preview.current?.pause()}},[])
 useEffect(()=>{if(!busy){setElapsed(0);return}const started=Date.now(),t=setInterval(()=>setElapsed(Math.floor((Date.now()-started)/1000)),1000);return()=>clearInterval(t)},[busy])
 const analyze=async()=>{
  if(!file||busy)return
  setBusy(true);setMessage('');setInitial([]);setStems([]);abort.current=new AbortController()
  try{
   if(file.size>120*1048576)throw new Error('Choose audio under 120 MB for this browser workspace.')
   const seconds=await localMetadata(file)
   if(seconds>300)throw new Error('Stem separation is limited to five minutes. Trim a shorter section first.')
   setStatus({phase:'read',message:'Reading audio…',progress:0})
   const parts=await separateLocally(file,setStatus,abort.current.signal,mode)
   setStems(parts)
   setInitial(parts.map(p=>({name:`${p.name}.wav`,blob:p.blob,muted:['Drums','Bass','Other instruments'].includes(p.name)})))
   setVersion(v=>v+1);setStatus(null);setMix('blend')
   setMessage(mode==='studio'?'AI stem processing completed. Listen to the individual stems: residual instrument bleed is possible.':'Fast Preview created approximate frequency-separated layers, NOT clean AI-isolated stems. Switch to Studio AI for improved separation.')
  }catch(e){
   if((e as Error).name!=='AbortError'){
    const raw=e instanceof Error?e.message:'Stem processing failed.'
    const friendly=/MODEL_DOWNLOAD_TIMEOUT/.test(raw)?'AI model download timed out. Check connection or browser cache and retry.':/GPU_START_TIMEOUT|LOCAL_START_TIMEOUT/.test(raw)?'AI engine failed to initialize. Try recent Chrome or Edge with more available memory.':/SEPARATION_TIMEOUT/.test(raw)?'Processing exceeded the device time limit. Try a shorter segment.':raw
    setMessage(`${friendly} Your audio was not automatically replaced with an approximate split. You may explicitly choose Fast Preview if needed.`)
   }
  }finally{setBusy(false);setStatus(null)}
 }
 const changeMix=(next:'blend'|'voice'|'instrumental')=>{setMix(next);window.dispatchEvent(new CustomEvent('audixo-stem-mix',{detail:{mode:next}}))}
 const saveStem=(name:string)=>{const stem=stems.find(s=>s.name===name);if(!stem)return;const url=URL.createObjectURL(stem.blob),a=document.createElement('a');const prefix=(file?.name||'audio').replace(/\.[^.]+$/,'').replace(/[\\/:*?"<>|]/g,' ').trim()||'audio';a.href=url;a.download=`${prefix} - ${name==='Music'?'Instrumental':'Vocals'} (Audixo).wav`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),120000)}
 const families=useMemo(()=>['All',...new Set(soundBank.map(s=>s.family))],[]),visibleBank=bankFamily==='All'?soundBank:soundBank.filter(s=>s.family===bankFamily)
 const createBankAudio=async(item:SoundBankItem,add=false)=>{if(bankBusy)return;setBankBusy(item.id);try{const blob=await createSoundBankClip(item);if(add){const detail={name:`${item.name}.wav`,blob};if(initial.length)window.dispatchEvent(new CustomEvent('audixo-import-audio',{detail}));else{setInitial([detail]);setVersion(v=>v+1)}setMessage(`${item.name} added as a new editable music layer.`)}else{preview.current?.pause();const url=URL.createObjectURL(blob),audio=new Audio(url);preview.current=audio;audio.onended=()=>URL.revokeObjectURL(url);audio.onerror=()=>URL.revokeObjectURL(url);await audio.play()}}catch(e){setMessage(e instanceof Error?e.message:'Music preview could not be created.')}finally{setBankBusy('')}}
 const order=['Lyrics / Vocals','Music','Drums','Bass','Other instruments']
 return <><SiteShell><Seo title="Audixo Vocal Extractor — Separate Voice, Music, Drums & Bass" description="Separate a song into editable Lyrics/Vocals, Music, Drums, Bass and Other Instrument tracks, then remix the stems or add music and beats." path="/tools/vocals"/><main className="page-shell ax25-vocals ax32-vocals"><section className="ax25-page-hero"><div className="ax25-kicker"><i/> VOCALS / MUSIC / STEMS</div><h1>Separate the song.<br/><em>Rebuild the mix.</em></h1><p>Extract the main singing voice from the backing music, then work with drums, bass and other instruments as independent tracks.</p></section>
  {initial.length===0&&<section className="ax25-stem-launch ax32-stem-launch"><div><span className={`ax25-engine-badge ${webGpu?'fast':'fallback'}`}><i/>{webGpu?'STUDIO AI · WEBGPU READY':threaded?'STUDIO AI · MULTI-CORE WASM':'STUDIO AI · COMPATIBILITY MODE'}</span><h2>Bring your song.</h2><p>Studio AI uses a Demucs stem model to estimate vocals, drums, bass and other instruments. The ONNX runtime is hosted in AUDIXO; the first run still downloads the large AI model once, then reuses the browser cache.</p><div className="ax32-separation-mode"><button className={mode==='studio'?'active':''} onClick={()=>setMode('studio')}><strong>Studio AI</strong><span>Highest-quality separation</span></button><button className={mode==='fast'?'active':''} onClick={()=>setMode('fast')}><strong>Fast Preview</strong><span>Quick approximate layers</span></button></div><div className="ax25-upload-actions"><button className="ax25-primary-button" disabled={busy} onClick={()=>input.current?.click()}>{file?'Change audio':'Choose audio'} <span>↗</span></button><button disabled={busy} onClick={()=>setLibrary(true)}>From Library</button></div>{file&&<div className="ax25-selected-audio"><span>♫</span><div><small>SELECTED SONG</small><strong>{file.name}</strong></div></div>}</div><div className="ax25-stem-visual ax32-stem-visual">{order.map((name,i)=><i key={name} style={{'--i':i} as CSSProperties}><small>{name.toUpperCase()}</small><b>▥</b></i>)}<button className="ax25-primary-button" disabled={!file||busy} onClick={analyze}>{busy?'Separating…':'Separate song'} <span>↗</span></button></div></section>}
  {busy&&<section className="ax25-stem-progress" role="status"><header><div><small>{status?.phase?.toUpperCase()||'PREPARING'}</small><strong>{status?.message||'Preparing the stem engine…'}</strong></div><b>{Math.floor(elapsed/60)}:{String(elapsed%60).padStart(2,'0')}</b></header><progress max="1" value={['read','init','engine'].includes(status?.phase||'read')?undefined:status?.progress||0}/><p>{mode==='studio'?'Studio AI keeps the real separation path active. On the first run, model download time depends on your connection and device.':'Fast Preview returns immediately but is an approximation, not a replacement for the Studio AI stems.'}</p><button onClick={()=>{abort.current?.abort();setStatus(null)}}>Cancel separation</button></section>}
  {message&&<div className="ax25-stem-message" role="status">{message}</div>}
  {stems.length>0&&<section className="ax25-stem-results ax32-stem-results"><header><small>SEPARATION COMPLETE</small><h2>Isolated tracks. Your mix.</h2><p>Music is the combined instrumental mix (Drums + Bass + Other). Do not unmute all five tracks together or the instruments will double.</p></header><div className="ax39-stem-actions"><div className="ax39-stem-modes" role="group" aria-label="Listen to separated stems"><button className={mix==='blend'?'active':''} aria-pressed={mix==='blend'} onClick={()=>changeMix('blend')}>♫ Full mix</button><button className={mix==='voice'?'active':''} aria-pressed={mix==='voice'} onClick={()=>changeMix('voice')}>◉ Vocals only</button><button className={mix==='instrumental'?'active':''} aria-pressed={mix==='instrumental'} onClick={()=>changeMix('instrumental')}>▦ Music only</button></div><div className="ax39-stem-saves"><button onClick={()=>saveStem('Lyrics / Vocals')}>↓ Vocals WAV</button><button onClick={()=>saveStem('Music')}>↓ Instrumental WAV</button></div></div><div>{order.map((name,i)=>{const stem=stems.find(s=>s.name===name);return stem?<article key={stem.name}><span>{String(i+1).padStart(2,'0')}</span><strong>{stem.name}</strong><i><b style={{width:`${stem.energy}%`}}/></i><em>{stem.mode==='ai'?'AI STEM':'APPROX.'}</em></article>:null})}</div></section>}
  {initial.length>0&&<section className="ax32-stem-workspace"><div className="ax32-stem-workspace-head"><div><small>STEM EDITOR</small><h2>Edit, mute, replace or rebuild.</h2><p>Every stem is editable in AUDIXO. Voice-only and Music-only buttons above immediately adjust mutes in the editor. Use the Studio controls, then add a music or beat layer from the library below.</p></div><button onClick={()=>{setInitial([]);setStems([]);setFile(null)}}>New separation</button></div><div className="ax32-stem-workspace-grid"><div className="ax32-stem-studio"><AudioStudio key={version} initialAudio={initial}/></div><aside className="ax32-bank-panel"><header><small>MUSIC & BEATS</small><strong>60 music & beat loops</strong><p>Add a generated music loop, beat, bassline, keys, guitar, synth, pad, percussion or transition to the current mix. These are creative additions, not detected stems.</p></header><nav>{families.map(f=><button key={f} className={bankFamily===f?'active':''} onClick={()=>setBankFamily(f)}>{f}</button>)}</nav><div className="ax32-bank-list">{visibleBank.map(item=><article key={item.id}><div><small>{item.family}</small><strong>{item.name}</strong><p>{item.note}</p></div><div><button disabled={!!bankBusy} onClick={()=>createBankAudio(item,false)}>{bankBusy===item.id?'Building…':'Preview'}</button><button className="add" disabled={!!bankBusy} onClick={()=>createBankAudio(item,true)}>+ Add</button></div></article>)}</div></aside></div></section>}
  <input hidden type="file" accept="audio/*,.mp3,.wav,.flac,.m4a,.ogg" ref={input} onChange={e=>{if(e.target.files?.[0])choose(e.target.files[0]);e.target.value=''}}/>
 </main></SiteShell><LibraryDrawer open={library} onClose={()=>setLibrary(false)} onSelect={useMix}/></>
}
